version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres_url
    ports:
      - "5432:5432"
    volumes:
      - database_pgdata:/var/lib/postgresql/data
      - ./initdb/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    networks:
      - url_shortener_network

networks:
  url_shortener_network:
    external: true

volumes:
  database_pgdata:
