version: '3.8'

services:
  analytics-service:
    image: analytics
    container_name: analytics
    build: .
    ports:
      - "3003:3003"
    environment:
      - DB_SSL=true
      - DB_HOST=postgres
      - DB_DATABASE_NAME=postgres_url
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_PORT=5432
      - DB_DIALECT=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - url_shortener_network

networks:
  url_shortener_network:
    external: true
