services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
      MONGO_INITDB_DATABASE: Url
    volumes:
      - ./mongo_data:/data/db  
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      