version: '3.8'

services:
  url-shortener-service:
    image: url-shortener
    container_name: shortener
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_SSL=true
      - DB_HOST=localhost
      - DB_DATABASE_NAME=postgres_url
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_PORT=5432
      - DB_DIALECT=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - url_shortener_network

networks:
  url_shortener_network:
    external: true
